### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by mooziii** [StckOverflw/kspigot-gradle-template#12]
this must be updated to 1.17 kspigot (remove shadow plugin, add library in plugin.yml...).
see [KSpigot Docs](https://bluefireoly.github.io/KSpigot/) for more

**Comment by louboecker** [comment]
Oh yeah I see now, PaperMc is finally stable, I have the Project already 1.17 ready on my Pc I was waiting for Paper to be stable. Will push in a few minutes

**Comment by louboecker** [comment]
[Update to 1.17](https://github.com/StckOverflw/kspigot-gradle-template/commit/451d1aab3a6b009313fb89ac425d38769257603a)
